# 校准配置文件

# 校准参数定义
# 注：参数范围和初始值已根据MFG模块调优结果更新（2025年版本）
parameters:
  - name: rho
    display_name: 贴现因子
    config_path: economics.rho
    bounds: [0.30, 0.60]
    initial_value: 0.40
    transform: null
    description: 个体对未来的贴现率，越大越重视未来（当前最优值0.40）
    
  - name: kappa
    display_name: 努力成本系数
    config_path: economics.kappa
    bounds: [1000.0, 4000.0]
    initial_value: 2000.0
    transform: null
    description: 努力的边际成本，越大个体越不愿意努力（当前最优值2000.0）
    
  - name: alpha_T
    display_name: T负效用系数
    config_path: economics.disutility_T.alpha
    bounds: [0.10, 0.60]
    initial_value: 0.30
    transform: null
    description: T偏离理想工作时间的负效用系数（当前最优值0.30）
    
  - name: gamma_T
    display_name: T状态更新系数
    config_path: economics.state_update.gamma_T
    bounds: [0.20, 0.50]
    initial_value: 0.30
    transform: null
    description: 努力对可工作时间T的影响系数（当前值0.30）
    
  - name: gamma_S
    display_name: S状态更新系数
    config_path: economics.state_update.gamma_S
    bounds: [0.30, 0.70]
    initial_value: 0.45
    transform: null
    description: 努力对技能水平S的影响系数（当前值0.45）
    
  - name: gamma_D
    display_name: D状态更新系数
    config_path: economics.state_update.gamma_D
    bounds: [0.30, 0.70]
    initial_value: 0.45
    transform: null
    description: 努力对数字素养D的影响系数（当前值0.45）
    
  - name: gamma_W
    display_name: W状态更新系数
    config_path: economics.state_update.gamma_W
    bounds: [0.10, 0.30]
    initial_value: 0.15
    transform: null
    description: 努力对期望工资W的影响系数，负向（当前值0.15）

# 目标矩定义
target_moments:
  config_file: CONFIG/target_moments.yaml
  weight_type: identity
  moments:
    - name: unemployment_rate
      display_name: 失业率
      weight: 1.0
      
    - name: mean_wage
      display_name: 平均工资
      weight: 1.0
      
    - name: std_wage
      display_name: 工资标准差
      weight: 1.0

# 优化算法设置
optimization:
  method: differential_evolution  # 并行优化算法
  options:
    maxiter: 100  # 减少迭代次数（因为每代会评估多个点）
    popsize: 32   # 种群大小：每代评估32个参数组合（并行）
    workers: 32   # 使用32个进程并行评估
    updating: deferred  # 延迟更新，允许并行
    atol: 1.0e-4
    tol: 1.0e-4
    polish: false  # 不做局部优化（太慢）
  alternative_methods:
    - Nelder-Mead  # 备用方案
    - L-BFGS-B
    - Powell

# 断点续跑设置
checkpoint:
  enabled: true
  save_frequency: 10
  keep_last_n: 3
  auto_resume: true
  checkpoint_dir: OUTPUT/calibration

# MFG求解设置
mfg_solver:
  config_path: CONFIG/mfg_config.yaml
  max_iterations: 150
  convergence_check: true
  population_adjustment: null

# 输出设置
output:
  output_dir: OUTPUT/calibration
  save_history: true
  save_plots: true
  save_checkpoint: true
  verbose: 2
  log_file: OUTPUT/calibration/calibration.log

# 两阶段校准设置
two_stage_calibration:
  enabled: true
  stage1:
    name: 敏感性分析引导
    use_sensitivity_results: true
    sensitivity_results_dir: OUTPUT/sensitivity_analysis
    adjust_bounds: true
    adjust_initial_values: true
  stage2:
    name: SMM精确校准
    use_adjusted_config: true

# 调试与测试设置
debug:
  quick_test: false
  quick_test_iterations: 5
  save_intermediate_results: true
  print_detailed_log: true

