economics:
  employment_utility:
    mean_wage: 4500.0
    std_wage: 1500.0
  disutility_T:
    enabled: true
    alpha: 0.3
  kappa: 2000.0
  rho: 0.40
  separation_rate:
    eta0: -3.46
    eta_D: -0.5
    eta_S: -0.8
    eta_T: -0.5
    eta_W: 0.05
    eta_age: -0.6
    eta_children: 0.15
    eta_edu: -0.3
    target_rate: 0.05
  state_update:
    gamma_D: 0.44999999999999996
    gamma_S: 0.44999999999999996
    gamma_T: 0.3
    gamma_W: 0.15
  unemployment_benefit:
    b0: 500.0
effort:
  a_max: 1.0
  a_min: 0.0
  a_points: 11
equilibrium:
  convergence:
    epsilon_V: 0.01
    epsilon_a: 0.01
    epsilon_u: 0.001
    use_relative_tol: true
  damping_factor: 0.3
  max_outer_iter: 100
market:
  initialization:
    initial_effort: 0.0
  target_theta: 1.5
paths:
  match_function_model: OUTPUT/logistic/match_function_model.pkl
  output_dir: OUTPUT/mfg
population:
  n_individuals: 10000
value_iteration:
  max_iter: 500
  tol: 0.0001
